#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 155
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum {
  sym_name = 1,
  anon_sym_LF = 2,
  anon_sym_SEMI = 3,
  anon_sym_if = 4,
  anon_sym_then = 5,
  anon_sym_else = 6,
  anon_sym_DQUOTE = 7,
  aux_sym_string_token1 = 8,
  sym_true = 9,
  sym_false = 10,
  sym_nil = 11,
  sym_number = 12,
  sym_symbol = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_DOT_DOT_DOT = 16,
  anon_sym_COMMA = 17,
  anon_sym_LBRACK = 18,
  anon_sym_RBRACK = 19,
  anon_sym_DOLLAR_LBRACE = 20,
  anon_sym_RBRACE = 21,
  anon_sym_POUND_LBRACE = 22,
  anon_sym_AT_LBRACE = 23,
  sym_source_file = 24,
  sym__line = 25,
  aux_sym__terminator = 26,
  sym_expression = 27,
  sym_if = 28,
  sym_literal = 29,
  sym_string = 30,
  sym__atom = 31,
  sym__collection = 32,
  sym_tuple = 33,
  sym__tuple_term = 34,
  sym_splat = 35,
  sym__tuple_entry = 36,
  aux_sym__separator = 37,
  sym__linear_collection = 38,
  sym_list = 39,
  sym_set = 40,
  sym_dict = 41,
  sym__dict_term = 42,
  sym__dict_entry = 43,
  sym_assoc = 44,
  sym_struct = 45,
  sym__struct_term = 46,
  sym__struct_entry = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_if_repeat1 = 49,
  aux_sym__linear_collection_repeat1 = 50,
  aux_sym_dict_repeat1 = 51,
  aux_sym_struct_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name] = "name",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_nil] = "nil",
  [sym_number] = "number",
  [sym_symbol] = "symbol",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT_DOT_DOT] = "...",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND_LBRACE] = "#{",
  [anon_sym_AT_LBRACE] = "@{",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [aux_sym__terminator] = "_terminator",
  [sym_expression] = "expression",
  [sym_if] = "if",
  [sym_literal] = "literal",
  [sym_string] = "string",
  [sym__atom] = "_atom",
  [sym__collection] = "_collection",
  [sym_tuple] = "tuple",
  [sym__tuple_term] = "_tuple_term",
  [sym_splat] = "splat",
  [sym__tuple_entry] = "_tuple_entry",
  [aux_sym__separator] = "_separator",
  [sym__linear_collection] = "_linear_collection",
  [sym_list] = "list",
  [sym_set] = "set",
  [sym_dict] = "dict",
  [sym__dict_term] = "_dict_term",
  [sym__dict_entry] = "_dict_entry",
  [sym_assoc] = "assoc",
  [sym_struct] = "struct",
  [sym__struct_term] = "_struct_term",
  [sym__struct_entry] = "_struct_entry",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_if_repeat1] = "if_repeat1",
  [aux_sym__linear_collection_repeat1] = "_linear_collection_repeat1",
  [aux_sym_dict_repeat1] = "dict_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name] = sym_name,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_nil] = sym_nil,
  [sym_number] = sym_number,
  [sym_symbol] = sym_symbol,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND_LBRACE] = anon_sym_POUND_LBRACE,
  [anon_sym_AT_LBRACE] = anon_sym_AT_LBRACE,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [aux_sym__terminator] = aux_sym__terminator,
  [sym_expression] = sym_expression,
  [sym_if] = sym_if,
  [sym_literal] = sym_literal,
  [sym_string] = sym_string,
  [sym__atom] = sym__atom,
  [sym__collection] = sym__collection,
  [sym_tuple] = sym_tuple,
  [sym__tuple_term] = sym__tuple_term,
  [sym_splat] = sym_splat,
  [sym__tuple_entry] = sym__tuple_entry,
  [aux_sym__separator] = aux_sym__separator,
  [sym__linear_collection] = sym__linear_collection,
  [sym_list] = sym_list,
  [sym_set] = sym_set,
  [sym_dict] = sym_dict,
  [sym__dict_term] = sym__dict_term,
  [sym__dict_entry] = sym__dict_entry,
  [sym_assoc] = sym_assoc,
  [sym_struct] = sym_struct,
  [sym__struct_term] = sym__struct_term,
  [sym__struct_entry] = sym__struct_entry,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_if_repeat1] = aux_sym_if_repeat1,
  [aux_sym__linear_collection_repeat1] = aux_sym__linear_collection_repeat1,
  [aux_sym_dict_repeat1] = aux_sym_dict_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__terminator] = {
    .visible = false,
    .named = false,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym__collection] = {
    .visible = false,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym__tuple_term] = {
    .visible = false,
    .named = true,
  },
  [sym_splat] = {
    .visible = true,
    .named = true,
  },
  [sym__tuple_entry] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__separator] = {
    .visible = false,
    .named = false,
  },
  [sym__linear_collection] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_dict] = {
    .visible = true,
    .named = true,
  },
  [sym__dict_term] = {
    .visible = false,
    .named = true,
  },
  [sym__dict_entry] = {
    .visible = false,
    .named = true,
  },
  [sym_assoc] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym__struct_term] = {
    .visible = false,
    .named = true,
  },
  [sym__struct_entry] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__linear_collection_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dict_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 3,
  [7] = 2,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 22,
  [23] = 17,
  [24] = 22,
  [25] = 18,
  [26] = 26,
  [27] = 21,
  [28] = 26,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 33,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 41,
  [43] = 40,
  [44] = 44,
  [45] = 45,
  [46] = 44,
  [47] = 45,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 52,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 54,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 70,
  [74] = 71,
  [75] = 72,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 79,
  [82] = 82,
  [83] = 78,
  [84] = 84,
  [85] = 85,
  [86] = 82,
  [87] = 87,
  [88] = 76,
  [89] = 87,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 93,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 96,
  [104] = 104,
  [105] = 94,
  [106] = 101,
  [107] = 98,
  [108] = 104,
  [109] = 109,
  [110] = 64,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 62,
  [115] = 115,
  [116] = 112,
  [117] = 61,
  [118] = 118,
  [119] = 51,
  [120] = 55,
  [121] = 58,
  [122] = 122,
  [123] = 50,
  [124] = 63,
  [125] = 125,
  [126] = 57,
  [127] = 127,
  [128] = 127,
  [129] = 129,
  [130] = 65,
  [131] = 53,
  [132] = 69,
  [133] = 109,
  [134] = 111,
  [135] = 60,
  [136] = 68,
  [137] = 122,
  [138] = 49,
  [139] = 118,
  [140] = 48,
  [141] = 67,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 143,
  [151] = 144,
  [152] = 145,
  [153] = 149,
  [154] = 146,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == '0') ADVANCE(17);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == '0') ADVANCE(17);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(23);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '0') ADVANCE(17);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == '{') ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == '{') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == '{') ADVANCE(30);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 9:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '!' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(8);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '!' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_AT_LBRACE);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'n') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'h') ADVANCE(10);
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 1},
  [144] = {.lex_state = 1},
  [145] = {.lex_state = 1},
  [146] = {.lex_state = 15},
  [147] = {.lex_state = 1},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 1},
  [150] = {.lex_state = 1},
  [151] = {.lex_state = 1},
  [152] = {.lex_state = 1},
  [153] = {.lex_state = 1},
  [154] = {.lex_state = 15},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND_LBRACE] = ACTIONS(1),
    [anon_sym_AT_LBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(148),
    [sym__line] = STATE(15),
    [aux_sym__terminator] = STATE(11),
    [sym_expression] = STATE(95),
    [sym_if] = STATE(121),
    [sym_literal] = STATE(121),
    [sym_string] = STATE(119),
    [sym__atom] = STATE(119),
    [sym__collection] = STATE(121),
    [sym_tuple] = STATE(121),
    [sym_list] = STATE(121),
    [sym_set] = STATE(121),
    [sym_dict] = STATE(121),
    [sym_struct] = STATE(121),
    [aux_sym_source_file_repeat1] = STATE(15),
    [sym_name] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_true] = ACTIONS(13),
    [sym_false] = ACTIONS(13),
    [sym_nil] = ACTIONS(13),
    [sym_number] = ACTIONS(13),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(19),
    [anon_sym_POUND_LBRACE] = ACTIONS(21),
    [anon_sym_AT_LBRACE] = ACTIONS(23),
  },
  [2] = {
    [sym_expression] = STATE(85),
    [sym_if] = STATE(58),
    [sym_literal] = STATE(58),
    [sym_string] = STATE(51),
    [sym__atom] = STATE(51),
    [sym__collection] = STATE(58),
    [sym_tuple] = STATE(58),
    [sym__tuple_term] = STATE(85),
    [sym_splat] = STATE(85),
    [sym__tuple_entry] = STATE(12),
    [aux_sym__separator] = STATE(8),
    [sym__linear_collection] = STATE(145),
    [sym_list] = STATE(58),
    [sym_set] = STATE(58),
    [sym_dict] = STATE(58),
    [sym_struct] = STATE(58),
    [aux_sym__linear_collection_repeat1] = STATE(12),
    [sym_name] = ACTIONS(25),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [sym_true] = ACTIONS(33),
    [sym_false] = ACTIONS(33),
    [sym_nil] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [sym_symbol] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(37),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(43),
    [anon_sym_POUND_LBRACE] = ACTIONS(45),
    [anon_sym_AT_LBRACE] = ACTIONS(47),
  },
  [3] = {
    [sym_expression] = STATE(85),
    [sym_if] = STATE(58),
    [sym_literal] = STATE(58),
    [sym_string] = STATE(51),
    [sym__atom] = STATE(51),
    [sym__collection] = STATE(58),
    [sym_tuple] = STATE(58),
    [sym__tuple_term] = STATE(85),
    [sym_splat] = STATE(85),
    [sym__tuple_entry] = STATE(12),
    [aux_sym__separator] = STATE(8),
    [sym__linear_collection] = STATE(144),
    [sym_list] = STATE(58),
    [sym_set] = STATE(58),
    [sym_dict] = STATE(58),
    [sym_struct] = STATE(58),
    [aux_sym__linear_collection_repeat1] = STATE(12),
    [sym_name] = ACTIONS(25),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [sym_true] = ACTIONS(33),
    [sym_false] = ACTIONS(33),
    [sym_nil] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [sym_symbol] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(37),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(43),
    [anon_sym_POUND_LBRACE] = ACTIONS(45),
    [anon_sym_AT_LBRACE] = ACTIONS(47),
  },
  [4] = {
    [sym_expression] = STATE(85),
    [sym_if] = STATE(58),
    [sym_literal] = STATE(58),
    [sym_string] = STATE(51),
    [sym__atom] = STATE(51),
    [sym__collection] = STATE(58),
    [sym_tuple] = STATE(58),
    [sym__tuple_term] = STATE(85),
    [sym_splat] = STATE(85),
    [sym__tuple_entry] = STATE(12),
    [aux_sym__separator] = STATE(8),
    [sym__linear_collection] = STATE(150),
    [sym_list] = STATE(58),
    [sym_set] = STATE(58),
    [sym_dict] = STATE(58),
    [sym_struct] = STATE(58),
    [aux_sym__linear_collection_repeat1] = STATE(12),
    [sym_name] = ACTIONS(25),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [sym_true] = ACTIONS(33),
    [sym_false] = ACTIONS(33),
    [sym_nil] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [sym_symbol] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(37),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(43),
    [anon_sym_POUND_LBRACE] = ACTIONS(45),
    [anon_sym_AT_LBRACE] = ACTIONS(47),
  },
  [5] = {
    [sym_expression] = STATE(85),
    [sym_if] = STATE(58),
    [sym_literal] = STATE(58),
    [sym_string] = STATE(51),
    [sym__atom] = STATE(51),
    [sym__collection] = STATE(58),
    [sym_tuple] = STATE(58),
    [sym__tuple_term] = STATE(85),
    [sym_splat] = STATE(85),
    [sym__tuple_entry] = STATE(12),
    [aux_sym__separator] = STATE(8),
    [sym__linear_collection] = STATE(143),
    [sym_list] = STATE(58),
    [sym_set] = STATE(58),
    [sym_dict] = STATE(58),
    [sym_struct] = STATE(58),
    [aux_sym__linear_collection_repeat1] = STATE(12),
    [sym_name] = ACTIONS(25),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [sym_true] = ACTIONS(33),
    [sym_false] = ACTIONS(33),
    [sym_nil] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [sym_symbol] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(37),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(43),
    [anon_sym_POUND_LBRACE] = ACTIONS(45),
    [anon_sym_AT_LBRACE] = ACTIONS(47),
  },
  [6] = {
    [sym_expression] = STATE(85),
    [sym_if] = STATE(58),
    [sym_literal] = STATE(58),
    [sym_string] = STATE(51),
    [sym__atom] = STATE(51),
    [sym__collection] = STATE(58),
    [sym_tuple] = STATE(58),
    [sym__tuple_term] = STATE(85),
    [sym_splat] = STATE(85),
    [sym__tuple_entry] = STATE(12),
    [aux_sym__separator] = STATE(8),
    [sym__linear_collection] = STATE(151),
    [sym_list] = STATE(58),
    [sym_set] = STATE(58),
    [sym_dict] = STATE(58),
    [sym_struct] = STATE(58),
    [aux_sym__linear_collection_repeat1] = STATE(12),
    [sym_name] = ACTIONS(25),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [sym_true] = ACTIONS(33),
    [sym_false] = ACTIONS(33),
    [sym_nil] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [sym_symbol] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(37),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(43),
    [anon_sym_POUND_LBRACE] = ACTIONS(45),
    [anon_sym_AT_LBRACE] = ACTIONS(47),
  },
  [7] = {
    [sym_expression] = STATE(85),
    [sym_if] = STATE(58),
    [sym_literal] = STATE(58),
    [sym_string] = STATE(51),
    [sym__atom] = STATE(51),
    [sym__collection] = STATE(58),
    [sym_tuple] = STATE(58),
    [sym__tuple_term] = STATE(85),
    [sym_splat] = STATE(85),
    [sym__tuple_entry] = STATE(12),
    [aux_sym__separator] = STATE(8),
    [sym__linear_collection] = STATE(152),
    [sym_list] = STATE(58),
    [sym_set] = STATE(58),
    [sym_dict] = STATE(58),
    [sym_struct] = STATE(58),
    [aux_sym__linear_collection_repeat1] = STATE(12),
    [sym_name] = ACTIONS(25),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [sym_true] = ACTIONS(33),
    [sym_false] = ACTIONS(33),
    [sym_nil] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [sym_symbol] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(37),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(43),
    [anon_sym_POUND_LBRACE] = ACTIONS(45),
    [anon_sym_AT_LBRACE] = ACTIONS(47),
  },
  [8] = {
    [sym_expression] = STATE(90),
    [sym_if] = STATE(58),
    [sym_literal] = STATE(58),
    [sym_string] = STATE(51),
    [sym__atom] = STATE(51),
    [sym__collection] = STATE(58),
    [sym_tuple] = STATE(58),
    [sym__tuple_term] = STATE(90),
    [sym_splat] = STATE(90),
    [sym__tuple_entry] = STATE(10),
    [aux_sym__separator] = STATE(32),
    [sym_list] = STATE(58),
    [sym_set] = STATE(58),
    [sym_dict] = STATE(58),
    [sym_struct] = STATE(58),
    [aux_sym__linear_collection_repeat1] = STATE(10),
    [sym_name] = ACTIONS(25),
    [anon_sym_LF] = ACTIONS(49),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [sym_true] = ACTIONS(33),
    [sym_false] = ACTIONS(33),
    [sym_nil] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [sym_symbol] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(37),
    [anon_sym_COMMA] = ACTIONS(51),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(43),
    [anon_sym_POUND_LBRACE] = ACTIONS(45),
    [anon_sym_AT_LBRACE] = ACTIONS(47),
  },
  [9] = {
    [sym_expression] = STATE(125),
    [sym_if] = STATE(58),
    [sym_literal] = STATE(58),
    [sym_string] = STATE(51),
    [sym__atom] = STATE(51),
    [sym__collection] = STATE(58),
    [sym_tuple] = STATE(58),
    [sym__tuple_term] = STATE(125),
    [sym_splat] = STATE(125),
    [sym__tuple_entry] = STATE(9),
    [sym_list] = STATE(58),
    [sym_set] = STATE(58),
    [sym_dict] = STATE(58),
    [sym_struct] = STATE(58),
    [aux_sym__linear_collection_repeat1] = STATE(9),
    [sym_name] = ACTIONS(53),
    [anon_sym_if] = ACTIONS(56),
    [anon_sym_DQUOTE] = ACTIONS(59),
    [sym_true] = ACTIONS(62),
    [sym_false] = ACTIONS(62),
    [sym_nil] = ACTIONS(62),
    [sym_number] = ACTIONS(65),
    [sym_symbol] = ACTIONS(65),
    [anon_sym_LPAREN] = ACTIONS(68),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(71),
    [anon_sym_LBRACK] = ACTIONS(74),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(77),
    [anon_sym_POUND_LBRACE] = ACTIONS(80),
    [anon_sym_AT_LBRACE] = ACTIONS(83),
  },
  [10] = {
    [sym_expression] = STATE(80),
    [sym_if] = STATE(58),
    [sym_literal] = STATE(58),
    [sym_string] = STATE(51),
    [sym__atom] = STATE(51),
    [sym__collection] = STATE(58),
    [sym_tuple] = STATE(58),
    [sym__tuple_term] = STATE(80),
    [sym_splat] = STATE(80),
    [sym__tuple_entry] = STATE(9),
    [sym_list] = STATE(58),
    [sym_set] = STATE(58),
    [sym_dict] = STATE(58),
    [sym_struct] = STATE(58),
    [aux_sym__linear_collection_repeat1] = STATE(9),
    [sym_name] = ACTIONS(25),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [sym_true] = ACTIONS(33),
    [sym_false] = ACTIONS(33),
    [sym_nil] = ACTIONS(33),
    [sym_number] = ACTIONS(88),
    [sym_symbol] = ACTIONS(88),
    [anon_sym_LPAREN] = ACTIONS(90),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(92),
    [anon_sym_LBRACK] = ACTIONS(94),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(96),
    [anon_sym_POUND_LBRACE] = ACTIONS(98),
    [anon_sym_AT_LBRACE] = ACTIONS(100),
  },
  [11] = {
    [sym__line] = STATE(14),
    [aux_sym__terminator] = STATE(38),
    [sym_expression] = STATE(99),
    [sym_if] = STATE(121),
    [sym_literal] = STATE(121),
    [sym_string] = STATE(119),
    [sym__atom] = STATE(119),
    [sym__collection] = STATE(121),
    [sym_tuple] = STATE(121),
    [sym_list] = STATE(121),
    [sym_set] = STATE(121),
    [sym_dict] = STATE(121),
    [sym_struct] = STATE(121),
    [aux_sym_source_file_repeat1] = STATE(14),
    [sym_name] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(102),
    [anon_sym_SEMI] = ACTIONS(104),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_true] = ACTIONS(13),
    [sym_false] = ACTIONS(13),
    [sym_nil] = ACTIONS(13),
    [sym_number] = ACTIONS(13),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(19),
    [anon_sym_POUND_LBRACE] = ACTIONS(21),
    [anon_sym_AT_LBRACE] = ACTIONS(23),
  },
  [12] = {
    [sym_expression] = STATE(90),
    [sym_if] = STATE(58),
    [sym_literal] = STATE(58),
    [sym_string] = STATE(51),
    [sym__atom] = STATE(51),
    [sym__collection] = STATE(58),
    [sym_tuple] = STATE(58),
    [sym__tuple_term] = STATE(90),
    [sym_splat] = STATE(90),
    [sym__tuple_entry] = STATE(9),
    [sym_list] = STATE(58),
    [sym_set] = STATE(58),
    [sym_dict] = STATE(58),
    [sym_struct] = STATE(58),
    [aux_sym__linear_collection_repeat1] = STATE(9),
    [sym_name] = ACTIONS(25),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [sym_true] = ACTIONS(33),
    [sym_false] = ACTIONS(33),
    [sym_nil] = ACTIONS(33),
    [sym_number] = ACTIONS(88),
    [sym_symbol] = ACTIONS(88),
    [anon_sym_LPAREN] = ACTIONS(90),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(92),
    [anon_sym_LBRACK] = ACTIONS(94),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(96),
    [anon_sym_POUND_LBRACE] = ACTIONS(98),
    [anon_sym_AT_LBRACE] = ACTIONS(100),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(106), 1,
      sym_name,
    ACTIONS(109), 1,
      anon_sym_if,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(124), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(130), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(133), 1,
      anon_sym_AT_LBRACE,
    STATE(129), 1,
      sym_expression,
    ACTIONS(118), 2,
      sym_number,
      sym_symbol,
    STATE(13), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(51), 2,
      sym_string,
      sym__atom,
    ACTIONS(115), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(58), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [55] = 14,
    ACTIONS(3), 1,
      sym_name,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(140), 1,
      anon_sym_LPAREN,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(144), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(146), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(148), 1,
      anon_sym_AT_LBRACE,
    STATE(100), 1,
      sym_expression,
    ACTIONS(138), 2,
      sym_number,
      sym_symbol,
    STATE(13), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(119), 2,
      sym_string,
      sym__atom,
    ACTIONS(13), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(121), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [110] = 14,
    ACTIONS(3), 1,
      sym_name,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(140), 1,
      anon_sym_LPAREN,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(144), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(146), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(148), 1,
      anon_sym_AT_LBRACE,
    STATE(99), 1,
      sym_expression,
    ACTIONS(138), 2,
      sym_number,
      sym_symbol,
    STATE(13), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(119), 2,
      sym_string,
      sym__atom,
    ACTIONS(13), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(121), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [165] = 13,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(98), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(100), 1,
      anon_sym_AT_LBRACE,
    STATE(142), 1,
      sym_expression,
    ACTIONS(88), 2,
      sym_number,
      sym_symbol,
    STATE(51), 2,
      sym_string,
      sym__atom,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(58), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [216] = 13,
    ACTIONS(3), 1,
      sym_name,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(140), 1,
      anon_sym_LPAREN,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(144), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(146), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(148), 1,
      anon_sym_AT_LBRACE,
    STATE(132), 1,
      sym_expression,
    ACTIONS(138), 2,
      sym_number,
      sym_symbol,
    STATE(119), 2,
      sym_string,
      sym__atom,
    ACTIONS(13), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(121), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [267] = 13,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(98), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(100), 1,
      anon_sym_AT_LBRACE,
    STATE(118), 1,
      sym_expression,
    ACTIONS(88), 2,
      sym_number,
      sym_symbol,
    STATE(51), 2,
      sym_string,
      sym__atom,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(58), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [318] = 13,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(98), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(100), 1,
      anon_sym_AT_LBRACE,
    STATE(111), 1,
      sym_expression,
    ACTIONS(88), 2,
      sym_number,
      sym_symbol,
    STATE(51), 2,
      sym_string,
      sym__atom,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(58), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [369] = 13,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(98), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(100), 1,
      anon_sym_AT_LBRACE,
    STATE(134), 1,
      sym_expression,
    ACTIONS(88), 2,
      sym_number,
      sym_symbol,
    STATE(51), 2,
      sym_string,
      sym__atom,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(58), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [420] = 13,
    ACTIONS(3), 1,
      sym_name,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(140), 1,
      anon_sym_LPAREN,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(144), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(146), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(148), 1,
      anon_sym_AT_LBRACE,
    STATE(130), 1,
      sym_expression,
    ACTIONS(138), 2,
      sym_number,
      sym_symbol,
    STATE(119), 2,
      sym_string,
      sym__atom,
    ACTIONS(13), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(121), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [471] = 13,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(98), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(100), 1,
      anon_sym_AT_LBRACE,
    STATE(127), 1,
      sym_expression,
    ACTIONS(88), 2,
      sym_number,
      sym_symbol,
    STATE(51), 2,
      sym_string,
      sym__atom,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(58), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [522] = 13,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(98), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(100), 1,
      anon_sym_AT_LBRACE,
    STATE(69), 1,
      sym_expression,
    ACTIONS(88), 2,
      sym_number,
      sym_symbol,
    STATE(51), 2,
      sym_string,
      sym__atom,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(58), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [573] = 13,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(98), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(100), 1,
      anon_sym_AT_LBRACE,
    STATE(128), 1,
      sym_expression,
    ACTIONS(88), 2,
      sym_number,
      sym_symbol,
    STATE(51), 2,
      sym_string,
      sym__atom,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(58), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [624] = 13,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(98), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(100), 1,
      anon_sym_AT_LBRACE,
    STATE(139), 1,
      sym_expression,
    ACTIONS(88), 2,
      sym_number,
      sym_symbol,
    STATE(51), 2,
      sym_string,
      sym__atom,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(58), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [675] = 13,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(98), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(100), 1,
      anon_sym_AT_LBRACE,
    STATE(68), 1,
      sym_expression,
    ACTIONS(88), 2,
      sym_number,
      sym_symbol,
    STATE(51), 2,
      sym_string,
      sym__atom,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(58), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [726] = 13,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(98), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(100), 1,
      anon_sym_AT_LBRACE,
    STATE(65), 1,
      sym_expression,
    ACTIONS(88), 2,
      sym_number,
      sym_symbol,
    STATE(51), 2,
      sym_string,
      sym__atom,
    ACTIONS(33), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(58), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [777] = 13,
    ACTIONS(3), 1,
      sym_name,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(140), 1,
      anon_sym_LPAREN,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(144), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(146), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(148), 1,
      anon_sym_AT_LBRACE,
    STATE(136), 1,
      sym_expression,
    ACTIONS(138), 2,
      sym_number,
      sym_symbol,
    STATE(119), 2,
      sym_string,
      sym__atom,
    ACTIONS(13), 3,
      sym_true,
      sym_false,
      sym_nil,
    STATE(121), 8,
      sym_if,
      sym_literal,
      sym__collection,
      sym_tuple,
      sym_list,
      sym_set,
      sym_dict,
      sym_struct,
  [828] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(152), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(150), 14,
      anon_sym_if,
      sym_name,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_nil,
      sym_number,
      sym_symbol,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      anon_sym_AT_LBRACE,
  [859] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(154), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(150), 14,
      anon_sym_if,
      sym_name,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_nil,
      sym_number,
      sym_symbol,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      anon_sym_AT_LBRACE,
  [890] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(156), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(150), 14,
      anon_sym_if,
      sym_name,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_nil,
      sym_number,
      sym_symbol,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      anon_sym_AT_LBRACE,
  [921] = 4,
    ACTIONS(160), 1,
      anon_sym_LF,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(158), 17,
      anon_sym_if,
      sym_name,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_nil,
      sym_number,
      sym_symbol,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND_LBRACE,
      anon_sym_AT_LBRACE,
  [950] = 5,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
    ACTIONS(170), 1,
      anon_sym_LF,
    ACTIONS(173), 1,
      anon_sym_SEMI,
    STATE(33), 1,
      aux_sym__terminator,
    ACTIONS(168), 13,
      anon_sym_if,
      sym_name,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_nil,
      sym_number,
      sym_symbol,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      anon_sym_AT_LBRACE,
  [978] = 5,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
    ACTIONS(180), 1,
      anon_sym_LF,
    ACTIONS(182), 1,
      anon_sym_SEMI,
    STATE(33), 1,
      aux_sym__terminator,
    ACTIONS(178), 13,
      anon_sym_if,
      sym_name,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_nil,
      sym_number,
      sym_symbol,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      anon_sym_AT_LBRACE,
  [1006] = 4,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(150), 14,
      anon_sym_if,
      sym_name,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_nil,
      sym_number,
      sym_symbol,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      anon_sym_AT_LBRACE,
  [1032] = 5,
    ACTIONS(180), 1,
      anon_sym_LF,
    ACTIONS(182), 1,
      anon_sym_SEMI,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
    STATE(33), 1,
      aux_sym__terminator,
    ACTIONS(178), 13,
      anon_sym_if,
      sym_name,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_nil,
      sym_number,
      sym_symbol,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      anon_sym_AT_LBRACE,
  [1060] = 5,
    ACTIONS(180), 1,
      anon_sym_LF,
    ACTIONS(182), 1,
      anon_sym_SEMI,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    STATE(33), 1,
      aux_sym__terminator,
    ACTIONS(178), 13,
      anon_sym_if,
      sym_name,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_nil,
      sym_number,
      sym_symbol,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      anon_sym_AT_LBRACE,
  [1088] = 4,
    ACTIONS(188), 1,
      anon_sym_LF,
    ACTIONS(191), 1,
      anon_sym_SEMI,
    STATE(38), 1,
      aux_sym__terminator,
    ACTIONS(168), 13,
      anon_sym_if,
      sym_name,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_nil,
      sym_number,
      sym_symbol,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      anon_sym_AT_LBRACE,
  [1113] = 4,
    ACTIONS(102), 1,
      anon_sym_LF,
    ACTIONS(104), 1,
      anon_sym_SEMI,
    STATE(38), 1,
      aux_sym__terminator,
    ACTIONS(178), 13,
      anon_sym_if,
      sym_name,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_nil,
      sym_number,
      sym_symbol,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      anon_sym_AT_LBRACE,
  [1138] = 8,
    ACTIONS(37), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      sym_name,
    ACTIONS(196), 1,
      sym_symbol,
    STATE(32), 1,
      aux_sym__separator,
    STATE(56), 2,
      sym__dict_entry,
      aux_sym_dict_repeat1,
    STATE(96), 3,
      sym_splat,
      sym__dict_term,
      sym_assoc,
  [1166] = 8,
    ACTIONS(37), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(196), 1,
      sym_symbol,
    ACTIONS(198), 1,
      sym_name,
    ACTIONS(200), 1,
      anon_sym_LF,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym__separator,
    STATE(66), 2,
      sym__dict_entry,
      aux_sym_dict_repeat1,
    STATE(94), 3,
      sym_splat,
      sym__dict_term,
      sym_assoc,
  [1194] = 8,
    ACTIONS(37), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(196), 1,
      sym_symbol,
    ACTIONS(204), 1,
      sym_name,
    ACTIONS(206), 1,
      anon_sym_LF,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      aux_sym__separator,
    STATE(54), 2,
      sym__dict_entry,
      aux_sym_dict_repeat1,
    STATE(105), 3,
      sym_splat,
      sym__dict_term,
      sym_assoc,
  [1222] = 8,
    ACTIONS(37), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      sym_symbol,
    ACTIONS(210), 1,
      sym_name,
    STATE(32), 1,
      aux_sym__separator,
    STATE(52), 2,
      sym__dict_entry,
      aux_sym_dict_repeat1,
    STATE(103), 3,
      sym_splat,
      sym__dict_term,
      sym_assoc,
  [1250] = 7,
    ACTIONS(196), 1,
      sym_symbol,
    ACTIONS(212), 1,
      sym_name,
    ACTIONS(214), 1,
      anon_sym_LF,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym__separator,
    STATE(89), 2,
      sym__struct_entry,
      aux_sym_struct_repeat1,
    STATE(108), 2,
      sym_assoc,
      sym__struct_term,
  [1274] = 7,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      sym_symbol,
    ACTIONS(218), 1,
      sym_name,
    STATE(32), 1,
      aux_sym__separator,
    STATE(76), 2,
      sym__struct_entry,
      aux_sym_struct_repeat1,
    STATE(97), 2,
      sym_assoc,
      sym__struct_term,
  [1298] = 7,
    ACTIONS(196), 1,
      sym_symbol,
    ACTIONS(220), 1,
      sym_name,
    ACTIONS(222), 1,
      anon_sym_LF,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym__separator,
    STATE(87), 2,
      sym__struct_entry,
      aux_sym_struct_repeat1,
    STATE(104), 2,
      sym_assoc,
      sym__struct_term,
  [1322] = 7,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      sym_symbol,
    ACTIONS(226), 1,
      sym_name,
    STATE(32), 1,
      aux_sym__separator,
    STATE(88), 2,
      sym__struct_entry,
      aux_sym_struct_repeat1,
    STATE(93), 2,
      sym_assoc,
      sym__struct_term,
  [1346] = 2,
    ACTIONS(228), 1,
      anon_sym_LF,
    ACTIONS(230), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1359] = 2,
    ACTIONS(232), 1,
      anon_sym_LF,
    ACTIONS(234), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1372] = 2,
    ACTIONS(236), 1,
      anon_sym_LF,
    ACTIONS(238), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1385] = 2,
    ACTIONS(240), 1,
      anon_sym_LF,
    ACTIONS(242), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1398] = 5,
    ACTIONS(92), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(244), 1,
      sym_name,
    ACTIONS(246), 1,
      sym_symbol,
    STATE(59), 2,
      sym__dict_entry,
      aux_sym_dict_repeat1,
    STATE(101), 3,
      sym_splat,
      sym__dict_term,
      sym_assoc,
  [1417] = 2,
    ACTIONS(248), 1,
      anon_sym_LF,
    ACTIONS(250), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1430] = 5,
    ACTIONS(92), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(246), 1,
      sym_symbol,
    ACTIONS(252), 1,
      sym_name,
    STATE(59), 2,
      sym__dict_entry,
      aux_sym_dict_repeat1,
    STATE(103), 3,
      sym_splat,
      sym__dict_term,
      sym_assoc,
  [1449] = 2,
    ACTIONS(254), 1,
      anon_sym_LF,
    ACTIONS(256), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1462] = 5,
    ACTIONS(92), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(246), 1,
      sym_symbol,
    ACTIONS(258), 1,
      sym_name,
    STATE(59), 2,
      sym__dict_entry,
      aux_sym_dict_repeat1,
    STATE(106), 3,
      sym_splat,
      sym__dict_term,
      sym_assoc,
  [1481] = 2,
    ACTIONS(260), 1,
      anon_sym_LF,
    ACTIONS(262), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1494] = 2,
    ACTIONS(264), 1,
      anon_sym_LF,
    ACTIONS(266), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1507] = 5,
    ACTIONS(268), 1,
      sym_name,
    ACTIONS(271), 1,
      sym_symbol,
    ACTIONS(274), 1,
      anon_sym_DOT_DOT_DOT,
    STATE(59), 2,
      sym__dict_entry,
      aux_sym_dict_repeat1,
    STATE(115), 3,
      sym_splat,
      sym__dict_term,
      sym_assoc,
  [1526] = 2,
    ACTIONS(277), 1,
      anon_sym_LF,
    ACTIONS(279), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1539] = 2,
    ACTIONS(281), 1,
      anon_sym_LF,
    ACTIONS(283), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1552] = 2,
    ACTIONS(285), 1,
      anon_sym_LF,
    ACTIONS(287), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1565] = 2,
    ACTIONS(289), 1,
      anon_sym_LF,
    ACTIONS(291), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1578] = 2,
    ACTIONS(293), 1,
      anon_sym_LF,
    ACTIONS(295), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1591] = 2,
    ACTIONS(297), 1,
      anon_sym_LF,
    ACTIONS(299), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1604] = 5,
    ACTIONS(92), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(246), 1,
      sym_symbol,
    ACTIONS(301), 1,
      sym_name,
    STATE(59), 2,
      sym__dict_entry,
      aux_sym_dict_repeat1,
    STATE(96), 3,
      sym_splat,
      sym__dict_term,
      sym_assoc,
  [1623] = 2,
    ACTIONS(303), 1,
      anon_sym_LF,
    ACTIONS(305), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1636] = 2,
    ACTIONS(307), 1,
      anon_sym_LF,
    ACTIONS(309), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1649] = 2,
    ACTIONS(311), 1,
      anon_sym_LF,
    ACTIONS(313), 7,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1662] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(317), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(315), 3,
      sym_name,
      sym_symbol,
      anon_sym_DOT_DOT_DOT,
  [1680] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(319), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(315), 3,
      sym_name,
      sym_symbol,
      anon_sym_DOT_DOT_DOT,
  [1698] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(321), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(315), 3,
      sym_name,
      sym_symbol,
      anon_sym_DOT_DOT_DOT,
  [1716] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(323), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(315), 3,
      sym_name,
      sym_symbol,
      anon_sym_DOT_DOT_DOT,
  [1734] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(325), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(315), 3,
      sym_name,
      sym_symbol,
      anon_sym_DOT_DOT_DOT,
  [1752] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(327), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(315), 3,
      sym_name,
      sym_symbol,
      anon_sym_DOT_DOT_DOT,
  [1770] = 4,
    ACTIONS(246), 1,
      sym_symbol,
    ACTIONS(329), 1,
      sym_name,
    STATE(77), 2,
      sym__struct_entry,
      aux_sym_struct_repeat1,
    STATE(107), 2,
      sym_assoc,
      sym__struct_term,
  [1785] = 4,
    ACTIONS(331), 1,
      sym_name,
    ACTIONS(334), 1,
      sym_symbol,
    STATE(77), 2,
      sym__struct_entry,
      aux_sym_struct_repeat1,
    STATE(113), 2,
      sym_assoc,
      sym__struct_term,
  [1800] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(339), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(337), 2,
      sym_name,
      sym_symbol,
  [1817] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(341), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(337), 2,
      sym_name,
      sym_symbol,
  [1834] = 4,
    ACTIONS(343), 1,
      anon_sym_LF,
    ACTIONS(345), 1,
      anon_sym_COMMA,
    STATE(29), 1,
      aux_sym__separator,
    ACTIONS(154), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1849] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(347), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(337), 2,
      sym_name,
      sym_symbol,
  [1866] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(349), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(337), 2,
      sym_name,
      sym_symbol,
  [1883] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(351), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(337), 2,
      sym_name,
      sym_symbol,
  [1900] = 4,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(315), 3,
      sym_name,
      sym_symbol,
      anon_sym_DOT_DOT_DOT,
  [1915] = 4,
    ACTIONS(353), 1,
      anon_sym_LF,
    ACTIONS(357), 1,
      anon_sym_COMMA,
    STATE(31), 1,
      aux_sym__separator,
    ACTIONS(355), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1930] = 5,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(359), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(337), 2,
      sym_name,
      sym_symbol,
  [1947] = 4,
    ACTIONS(246), 1,
      sym_symbol,
    ACTIONS(361), 1,
      sym_name,
    STATE(77), 2,
      sym__struct_entry,
      aux_sym_struct_repeat1,
    STATE(93), 2,
      sym_assoc,
      sym__struct_term,
  [1962] = 4,
    ACTIONS(246), 1,
      sym_symbol,
    ACTIONS(363), 1,
      sym_name,
    STATE(77), 2,
      sym__struct_entry,
      aux_sym_struct_repeat1,
    STATE(98), 2,
      sym_assoc,
      sym__struct_term,
  [1977] = 4,
    ACTIONS(246), 1,
      sym_symbol,
    ACTIONS(365), 1,
      sym_name,
    STATE(77), 2,
      sym__struct_entry,
      aux_sym_struct_repeat1,
    STATE(97), 2,
      sym_assoc,
      sym__struct_term,
  [1992] = 4,
    ACTIONS(367), 1,
      anon_sym_LF,
    ACTIONS(369), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym__separator,
    ACTIONS(156), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [2007] = 2,
    ACTIONS(371), 1,
      anon_sym_LF,
    ACTIONS(373), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [2017] = 4,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym__separator,
    ACTIONS(337), 2,
      sym_name,
      sym_symbol,
  [2031] = 4,
    ACTIONS(351), 1,
      anon_sym_RBRACE,
    ACTIONS(375), 1,
      anon_sym_LF,
    ACTIONS(377), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym__separator,
  [2044] = 4,
    ACTIONS(379), 1,
      anon_sym_LF,
    ACTIONS(381), 1,
      anon_sym_COMMA,
    ACTIONS(383), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      aux_sym__separator,
  [2057] = 4,
    ACTIONS(385), 1,
      ts_builtin_sym_end,
    ACTIONS(387), 1,
      anon_sym_LF,
    ACTIONS(389), 1,
      anon_sym_SEMI,
    STATE(34), 1,
      aux_sym__terminator,
  [2070] = 4,
    ACTIONS(325), 1,
      anon_sym_RBRACE,
    ACTIONS(391), 1,
      anon_sym_LF,
    ACTIONS(393), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym__separator,
  [2083] = 4,
    ACTIONS(339), 1,
      anon_sym_RBRACE,
    ACTIONS(395), 1,
      anon_sym_LF,
    ACTIONS(397), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      aux_sym__separator,
  [2096] = 4,
    ACTIONS(341), 1,
      anon_sym_RBRACE,
    ACTIONS(399), 1,
      anon_sym_LF,
    ACTIONS(401), 1,
      anon_sym_COMMA,
    STATE(82), 1,
      aux_sym__separator,
  [2109] = 4,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
    ACTIONS(403), 1,
      anon_sym_LF,
    ACTIONS(405), 1,
      anon_sym_SEMI,
    STATE(37), 1,
      aux_sym__terminator,
  [2122] = 4,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    ACTIONS(407), 1,
      anon_sym_LF,
    ACTIONS(409), 1,
      anon_sym_SEMI,
    STATE(36), 1,
      aux_sym__terminator,
  [2135] = 4,
    ACTIONS(327), 1,
      anon_sym_RBRACE,
    ACTIONS(411), 1,
      anon_sym_LF,
    ACTIONS(413), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym__separator,
  [2148] = 3,
    ACTIONS(415), 1,
      anon_sym_LF,
    STATE(102), 1,
      aux_sym_if_repeat1,
    ACTIONS(418), 2,
      anon_sym_then,
      anon_sym_else,
  [2159] = 4,
    ACTIONS(319), 1,
      anon_sym_RBRACE,
    ACTIONS(420), 1,
      anon_sym_LF,
    ACTIONS(422), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym__separator,
  [2172] = 4,
    ACTIONS(424), 1,
      anon_sym_LF,
    ACTIONS(426), 1,
      anon_sym_COMMA,
    ACTIONS(428), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      aux_sym__separator,
  [2185] = 4,
    ACTIONS(430), 1,
      anon_sym_LF,
    ACTIONS(432), 1,
      anon_sym_COMMA,
    ACTIONS(434), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym__separator,
  [2198] = 4,
    ACTIONS(321), 1,
      anon_sym_RBRACE,
    ACTIONS(436), 1,
      anon_sym_LF,
    ACTIONS(438), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym__separator,
  [2211] = 4,
    ACTIONS(347), 1,
      anon_sym_RBRACE,
    ACTIONS(440), 1,
      anon_sym_LF,
    ACTIONS(442), 1,
      anon_sym_COMMA,
    STATE(86), 1,
      aux_sym__separator,
  [2224] = 4,
    ACTIONS(444), 1,
      anon_sym_LF,
    ACTIONS(446), 1,
      anon_sym_COMMA,
    ACTIONS(448), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      aux_sym__separator,
  [2237] = 3,
    ACTIONS(450), 1,
      anon_sym_LF,
    ACTIONS(452), 1,
      anon_sym_else,
    STATE(102), 1,
      aux_sym_if_repeat1,
  [2247] = 2,
    ACTIONS(295), 1,
      anon_sym_SEMI,
    ACTIONS(293), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2255] = 3,
    ACTIONS(452), 1,
      anon_sym_else,
    ACTIONS(454), 1,
      anon_sym_LF,
    STATE(122), 1,
      aux_sym_if_repeat1,
  [2265] = 3,
    ACTIONS(450), 1,
      anon_sym_LF,
    ACTIONS(456), 1,
      anon_sym_then,
    STATE(102), 1,
      aux_sym_if_repeat1,
  [2275] = 3,
    ACTIONS(458), 1,
      anon_sym_LF,
    ACTIONS(460), 1,
      anon_sym_COMMA,
    STATE(92), 1,
      aux_sym__separator,
  [2285] = 2,
    ACTIONS(287), 1,
      anon_sym_SEMI,
    ACTIONS(285), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2293] = 3,
    ACTIONS(462), 1,
      anon_sym_LF,
    ACTIONS(464), 1,
      anon_sym_COMMA,
    STATE(84), 1,
      aux_sym__separator,
  [2303] = 3,
    ACTIONS(450), 1,
      anon_sym_LF,
    ACTIONS(466), 1,
      anon_sym_then,
    STATE(102), 1,
      aux_sym_if_repeat1,
  [2313] = 2,
    ACTIONS(283), 1,
      anon_sym_SEMI,
    ACTIONS(281), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2321] = 3,
    ACTIONS(468), 1,
      anon_sym_LF,
    ACTIONS(470), 1,
      anon_sym_then,
    STATE(116), 1,
      aux_sym_if_repeat1,
  [2331] = 2,
    ACTIONS(242), 1,
      anon_sym_SEMI,
    ACTIONS(240), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2339] = 2,
    ACTIONS(256), 1,
      anon_sym_SEMI,
    ACTIONS(254), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2347] = 2,
    ACTIONS(266), 1,
      anon_sym_SEMI,
    ACTIONS(264), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2355] = 3,
    ACTIONS(450), 1,
      anon_sym_LF,
    ACTIONS(472), 1,
      anon_sym_else,
    STATE(102), 1,
      aux_sym_if_repeat1,
  [2365] = 2,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    ACTIONS(236), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2373] = 2,
    ACTIONS(291), 1,
      anon_sym_SEMI,
    ACTIONS(289), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2381] = 3,
    ACTIONS(474), 1,
      anon_sym_LF,
    ACTIONS(476), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym__separator,
  [2391] = 2,
    ACTIONS(262), 1,
      anon_sym_SEMI,
    ACTIONS(260), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2399] = 3,
    ACTIONS(478), 1,
      anon_sym_LF,
    ACTIONS(480), 1,
      anon_sym_else,
    STATE(109), 1,
      aux_sym_if_repeat1,
  [2409] = 3,
    ACTIONS(482), 1,
      anon_sym_LF,
    ACTIONS(484), 1,
      anon_sym_else,
    STATE(133), 1,
      aux_sym_if_repeat1,
  [2419] = 3,
    ACTIONS(486), 1,
      anon_sym_LF,
    ACTIONS(488), 1,
      anon_sym_SEMI,
    STATE(39), 1,
      aux_sym__terminator,
  [2429] = 2,
    ACTIONS(299), 1,
      anon_sym_SEMI,
    ACTIONS(297), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2437] = 2,
    ACTIONS(250), 1,
      anon_sym_SEMI,
    ACTIONS(248), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2445] = 2,
    ACTIONS(313), 1,
      anon_sym_SEMI,
    ACTIONS(311), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2453] = 3,
    ACTIONS(450), 1,
      anon_sym_LF,
    ACTIONS(490), 1,
      anon_sym_else,
    STATE(102), 1,
      aux_sym_if_repeat1,
  [2463] = 3,
    ACTIONS(490), 1,
      anon_sym_else,
    ACTIONS(492), 1,
      anon_sym_LF,
    STATE(137), 1,
      aux_sym_if_repeat1,
  [2473] = 2,
    ACTIONS(279), 1,
      anon_sym_SEMI,
    ACTIONS(277), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2481] = 2,
    ACTIONS(309), 1,
      anon_sym_SEMI,
    ACTIONS(307), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2489] = 3,
    ACTIONS(450), 1,
      anon_sym_LF,
    ACTIONS(494), 1,
      anon_sym_else,
    STATE(102), 1,
      aux_sym_if_repeat1,
  [2499] = 2,
    ACTIONS(234), 1,
      anon_sym_SEMI,
    ACTIONS(232), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2507] = 3,
    ACTIONS(496), 1,
      anon_sym_LF,
    ACTIONS(498), 1,
      anon_sym_then,
    STATE(112), 1,
      aux_sym_if_repeat1,
  [2517] = 2,
    ACTIONS(230), 1,
      anon_sym_SEMI,
    ACTIONS(228), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2525] = 2,
    ACTIONS(305), 1,
      anon_sym_SEMI,
    ACTIONS(303), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [2533] = 2,
    ACTIONS(500), 1,
      anon_sym_LF,
    ACTIONS(502), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2541] = 1,
    ACTIONS(504), 1,
      anon_sym_RBRACE,
  [2545] = 1,
    ACTIONS(506), 1,
      anon_sym_RBRACK,
  [2549] = 1,
    ACTIONS(508), 1,
      anon_sym_RPAREN,
  [2553] = 1,
    ACTIONS(510), 1,
      aux_sym_string_token1,
  [2557] = 1,
    ACTIONS(512), 1,
      sym_name,
  [2561] = 1,
    ACTIONS(514), 1,
      ts_builtin_sym_end,
  [2565] = 1,
    ACTIONS(516), 1,
      anon_sym_DQUOTE,
  [2569] = 1,
    ACTIONS(518), 1,
      anon_sym_RBRACE,
  [2573] = 1,
    ACTIONS(520), 1,
      anon_sym_RBRACK,
  [2577] = 1,
    ACTIONS(522), 1,
      anon_sym_RPAREN,
  [2581] = 1,
    ACTIONS(524), 1,
      anon_sym_DQUOTE,
  [2585] = 1,
    ACTIONS(526), 1,
      aux_sym_string_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 55,
  [SMALL_STATE(15)] = 110,
  [SMALL_STATE(16)] = 165,
  [SMALL_STATE(17)] = 216,
  [SMALL_STATE(18)] = 267,
  [SMALL_STATE(19)] = 318,
  [SMALL_STATE(20)] = 369,
  [SMALL_STATE(21)] = 420,
  [SMALL_STATE(22)] = 471,
  [SMALL_STATE(23)] = 522,
  [SMALL_STATE(24)] = 573,
  [SMALL_STATE(25)] = 624,
  [SMALL_STATE(26)] = 675,
  [SMALL_STATE(27)] = 726,
  [SMALL_STATE(28)] = 777,
  [SMALL_STATE(29)] = 828,
  [SMALL_STATE(30)] = 859,
  [SMALL_STATE(31)] = 890,
  [SMALL_STATE(32)] = 921,
  [SMALL_STATE(33)] = 950,
  [SMALL_STATE(34)] = 978,
  [SMALL_STATE(35)] = 1006,
  [SMALL_STATE(36)] = 1032,
  [SMALL_STATE(37)] = 1060,
  [SMALL_STATE(38)] = 1088,
  [SMALL_STATE(39)] = 1113,
  [SMALL_STATE(40)] = 1138,
  [SMALL_STATE(41)] = 1166,
  [SMALL_STATE(42)] = 1194,
  [SMALL_STATE(43)] = 1222,
  [SMALL_STATE(44)] = 1250,
  [SMALL_STATE(45)] = 1274,
  [SMALL_STATE(46)] = 1298,
  [SMALL_STATE(47)] = 1322,
  [SMALL_STATE(48)] = 1346,
  [SMALL_STATE(49)] = 1359,
  [SMALL_STATE(50)] = 1372,
  [SMALL_STATE(51)] = 1385,
  [SMALL_STATE(52)] = 1398,
  [SMALL_STATE(53)] = 1417,
  [SMALL_STATE(54)] = 1430,
  [SMALL_STATE(55)] = 1449,
  [SMALL_STATE(56)] = 1462,
  [SMALL_STATE(57)] = 1481,
  [SMALL_STATE(58)] = 1494,
  [SMALL_STATE(59)] = 1507,
  [SMALL_STATE(60)] = 1526,
  [SMALL_STATE(61)] = 1539,
  [SMALL_STATE(62)] = 1552,
  [SMALL_STATE(63)] = 1565,
  [SMALL_STATE(64)] = 1578,
  [SMALL_STATE(65)] = 1591,
  [SMALL_STATE(66)] = 1604,
  [SMALL_STATE(67)] = 1623,
  [SMALL_STATE(68)] = 1636,
  [SMALL_STATE(69)] = 1649,
  [SMALL_STATE(70)] = 1662,
  [SMALL_STATE(71)] = 1680,
  [SMALL_STATE(72)] = 1698,
  [SMALL_STATE(73)] = 1716,
  [SMALL_STATE(74)] = 1734,
  [SMALL_STATE(75)] = 1752,
  [SMALL_STATE(76)] = 1770,
  [SMALL_STATE(77)] = 1785,
  [SMALL_STATE(78)] = 1800,
  [SMALL_STATE(79)] = 1817,
  [SMALL_STATE(80)] = 1834,
  [SMALL_STATE(81)] = 1849,
  [SMALL_STATE(82)] = 1866,
  [SMALL_STATE(83)] = 1883,
  [SMALL_STATE(84)] = 1900,
  [SMALL_STATE(85)] = 1915,
  [SMALL_STATE(86)] = 1930,
  [SMALL_STATE(87)] = 1947,
  [SMALL_STATE(88)] = 1962,
  [SMALL_STATE(89)] = 1977,
  [SMALL_STATE(90)] = 1992,
  [SMALL_STATE(91)] = 2007,
  [SMALL_STATE(92)] = 2017,
  [SMALL_STATE(93)] = 2031,
  [SMALL_STATE(94)] = 2044,
  [SMALL_STATE(95)] = 2057,
  [SMALL_STATE(96)] = 2070,
  [SMALL_STATE(97)] = 2083,
  [SMALL_STATE(98)] = 2096,
  [SMALL_STATE(99)] = 2109,
  [SMALL_STATE(100)] = 2122,
  [SMALL_STATE(101)] = 2135,
  [SMALL_STATE(102)] = 2148,
  [SMALL_STATE(103)] = 2159,
  [SMALL_STATE(104)] = 2172,
  [SMALL_STATE(105)] = 2185,
  [SMALL_STATE(106)] = 2198,
  [SMALL_STATE(107)] = 2211,
  [SMALL_STATE(108)] = 2224,
  [SMALL_STATE(109)] = 2237,
  [SMALL_STATE(110)] = 2247,
  [SMALL_STATE(111)] = 2255,
  [SMALL_STATE(112)] = 2265,
  [SMALL_STATE(113)] = 2275,
  [SMALL_STATE(114)] = 2285,
  [SMALL_STATE(115)] = 2293,
  [SMALL_STATE(116)] = 2303,
  [SMALL_STATE(117)] = 2313,
  [SMALL_STATE(118)] = 2321,
  [SMALL_STATE(119)] = 2331,
  [SMALL_STATE(120)] = 2339,
  [SMALL_STATE(121)] = 2347,
  [SMALL_STATE(122)] = 2355,
  [SMALL_STATE(123)] = 2365,
  [SMALL_STATE(124)] = 2373,
  [SMALL_STATE(125)] = 2381,
  [SMALL_STATE(126)] = 2391,
  [SMALL_STATE(127)] = 2399,
  [SMALL_STATE(128)] = 2409,
  [SMALL_STATE(129)] = 2419,
  [SMALL_STATE(130)] = 2429,
  [SMALL_STATE(131)] = 2437,
  [SMALL_STATE(132)] = 2445,
  [SMALL_STATE(133)] = 2453,
  [SMALL_STATE(134)] = 2463,
  [SMALL_STATE(135)] = 2473,
  [SMALL_STATE(136)] = 2481,
  [SMALL_STATE(137)] = 2489,
  [SMALL_STATE(138)] = 2499,
  [SMALL_STATE(139)] = 2507,
  [SMALL_STATE(140)] = 2517,
  [SMALL_STATE(141)] = 2525,
  [SMALL_STATE(142)] = 2533,
  [SMALL_STATE(143)] = 2541,
  [SMALL_STATE(144)] = 2545,
  [SMALL_STATE(145)] = 2549,
  [SMALL_STATE(146)] = 2553,
  [SMALL_STATE(147)] = 2557,
  [SMALL_STATE(148)] = 2561,
  [SMALL_STATE(149)] = 2565,
  [SMALL_STATE(150)] = 2569,
  [SMALL_STATE(151)] = 2573,
  [SMALL_STATE(152)] = 2577,
  [SMALL_STATE(153)] = 2581,
  [SMALL_STATE(154)] = 2585,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(154),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(146),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(147),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__linear_collection_repeat1, 2), SHIFT_REPEAT(58),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__linear_collection_repeat1, 2), SHIFT_REPEAT(18),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__linear_collection_repeat1, 2), SHIFT_REPEAT(146),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__linear_collection_repeat1, 2), SHIFT_REPEAT(51),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__linear_collection_repeat1, 2), SHIFT_REPEAT(51),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__linear_collection_repeat1, 2), SHIFT_REPEAT(7),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__linear_collection_repeat1, 2), SHIFT_REPEAT(147),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__linear_collection_repeat1, 2), SHIFT_REPEAT(6),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__linear_collection_repeat1, 2), SHIFT_REPEAT(5),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__linear_collection_repeat1, 2), SHIFT_REPEAT(42),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__linear_collection_repeat1, 2), SHIFT_REPEAT(46),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(58),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(18),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(146),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(7),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(5),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(42),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(46),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__tuple_entry, 2),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__linear_collection, 4),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__linear_collection, 3),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__linear_collection, 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__separator, 2),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__separator, 2), SHIFT_REPEAT(32),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__separator, 2), SHIFT_REPEAT(32),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__terminator, 2),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__terminator, 2),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__terminator, 2), SHIFT_REPEAT(33),
  [173] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__terminator, 2), SHIFT_REPEAT(33),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__terminator, 2), SHIFT_REPEAT(38),
  [191] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__terminator, 2), SHIFT_REPEAT(38),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 6),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 3),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 3),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 3),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [268] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2), SHIFT_REPEAT(115),
  [271] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2), SHIFT_REPEAT(16),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2), SHIFT_REPEAT(147),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 3),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 4),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 4),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4),
  [287] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 4),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 5),
  [291] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 5),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 5),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 6),
  [299] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 6),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 6),
  [305] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 6),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 7),
  [309] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 7),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 8),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 8),
  [315] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dict_entry, 2),
  [317] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [319] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [321] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [323] = {.entry = {.count = 1, .reusable = false}}, SHIFT(141),
  [325] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [327] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [331] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2), SHIFT_REPEAT(113),
  [334] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2), SHIFT_REPEAT(16),
  [337] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__struct_entry, 2),
  [339] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [341] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [345] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [347] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [349] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [351] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [355] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__linear_collection, 1),
  [357] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [359] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [369] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_splat, 2),
  [373] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_splat, 2),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [377] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [381] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [383] = {.entry = {.count = 1, .reusable = false}}, SHIFT(138),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [389] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [393] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [397] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [401] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [405] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [409] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [413] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [415] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_repeat1, 2), SHIFT_REPEAT(102),
  [418] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_repeat1, 2),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [422] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [426] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [428] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [432] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [434] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [436] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [438] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [440] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [442] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [444] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [446] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [448] = {.entry = {.count = 1, .reusable = false}}, SHIFT(135),
  [450] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [452] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [454] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [456] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [458] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [460] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [462] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [464] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [466] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [468] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [470] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [472] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [474] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [476] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [478] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [480] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [482] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [484] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [486] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [488] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [490] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [492] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [494] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [496] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [498] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [500] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assoc, 2),
  [502] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assoc, 2),
  [504] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [506] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [508] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [510] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [512] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [514] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [516] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [518] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [520] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [522] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [524] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [526] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_Ludus(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_name,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
